### ISSUE TITLE
简单CNN原理复现问题

### ISSUE THREAD

**Issue by cuixing158** [ShiqiYu/SimpleCNNbyCPP#2]
初步看了下，simpleCNN仍然使用的是pytorch深度学习库复现，我在去年也类似复现了一个简单的手写数字识别，不调用任何第三方框架，从数学原理上实现，逐个公式各个击破，有兴趣详看参考这里 https://github.com/cuixing158/DeeplearningPractice

**Comment by fengyuentau** [comment]
您好，您应该仔细阅读readme。我们只使用了pytorch来训练模型。
